[[main]]
  name = "Startseite"
  url = "/"
  weight = 10
  [main.params]
    icon = "home"

[[main]]
  name = "Grundlagen"
  url = "/grundlagen/"
  weight = 20

[[main]]
  name = "Übungen"
  url = "/uebungen/"
  weight = 30

[[main]]
  identifier = "zielgruppen"
  name = "Für wen?"
  weight = 40

[[main]]
  parent = "zielgruppen"
  name = "Anfänger"
  url = "/categories/anfaenger/"
  weight = 1

[[main]]
  parent = "zielgruppen"
  name = "Fortgeschrittene"
  url = "/categories/fortgeschrittene/"
  weight = 2

[[main]]
  parent = "zielgruppen"
  name = "Frauen"
  url = "/categories/frauen/"
  weight = 3

[[main]]
  parent = "zielgruppen"
  name = "Senioren (50+)"
  url = "/categories/senioren/"
  weight = 4

[[main]]
  parent = "zielgruppen"
  name = "Jugend & Kinder"
  url = "/categories/jugend/"
  weight = 5

[[main]]
  identifier = "trainingsort"
  name = "Wo trainieren?"
  weight = 50

[[main]]
  parent = "trainingsort"
  name = "Zuhause"
  url = "/categories/zuhause/"
  weight = 1

[[main]]
  parent = "trainingsort"
  name = "Fitnessstudio"
  url = "/categories/fitnessstudio/"
  weight = 2

[[main]]
  parent = "trainingsort"
  name = "Outdoor"
  url = "/categories/outdoor/"
  weight = 3

[[main]]
  parent = "trainingsort"
  name = "Park-Finder"
  url = "/tools/outdoor-fitnessparks/"
  weight = 4

[[main]]
  name = "Tools"
  url = "/tools/"
  weight = 60

[[social]]
  identifier = "email"
  name = "Email"
  url = "mailto:kontakt@krafttraining.online"
  [social.params]
    icon = "mail"
